const mongoose = require('mongoose');

const specialEventSchema = mongoose.Schema(
	{
		_id: mongoose.Schema.Types.ObjectId,
		user_id: String,
		last_updated: Number,
		powerfest: Number,
		powerfestFtAmt: Number,
		powerfestBronze: Boolean,
		powerfestSilver: Boolean,
		powerfestTrophy: Boolean,
		powerfestBronzeAmt: Number,
		powerfestSilverAmt: Number,
		powerfestTrophyAmt: Number,
		monsterseries: Number,
		monsterFtAmt: Number,
		monsterBronze: Boolean,
		monsterSilver: Boolean,
		monsterTrophy: Boolean,
		monsterBronzeAmt: Number,
		monsterSilverAmt: Number,
		monsterTrophyAmt: Number,
		koseries: Number,
		koFtAmt: Number,
		koBronze: Boolean,
		koSilver: Boolean,
		koTrophy: Boolean,
		koBronzeAmt: Number,
		koSilverAmt: Number,
		koTrophyAmt: Number,
		omahaseries: Number,
		omahaFtAmt: Number,
		omahaBronze: Boolean,
		omahaSilver: Boolean,
		omahaTrophy: Boolean,
		omahaBronzeAmt: Number,
		omahaSilverAmt: Number,
		omahaTrophyAmt: Number,
		millionsonline: Number,
		millionsFtAmt: Number,
		millionsBronze: Boolean,
		millionsSilver: Boolean,
		millionsTrophy: Boolean,
		millionsBronzeAmt: Number,
		millionsSilverAmt: Number,
		millionsTrophyAmt: Number
	},
	{ versionKey: false }
);

module.exports = mongoose.model('SpecialEvents', specialEventSchema);
